### ISSUE TITLE
Create station from the SDK using default values

### ISSUE THREAD

**Issue by yanivbh1** [Memphis-OS/memphis.js#22]
Hey,
Please allow the user to create a station from this syntax alone (consumer and producer) - 
```
ordersStation_producer = await memphis.producer({
            stationName: "orders",
            producerName: "order_service"
        });
```

In return output, in case a new station actually created, please notify me of that fact + its details. For example - 
`info: Memphis - Station <name> created. Retention="7 days", Storage Type=File, Replicas=1`

**Comment by idanasulinmemphis** [comment]
Added as a new feature in the control plane repo
